name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish, must be a git tag'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #      - name: Check out specified version
      #        run: |
      #          git fetch --all --tags
      #          git checkout ${{ inputs.version }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execution permissions for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Check JReleaser Config
        run: ./gradlew jreleaserConfig

      #      - name: Ensure a clean deployment
      #        run: ./gradlew clean

      - name: Prepare artifacts for deployment
        run: ./gradlew publish

      - name: Deploy and release
        run: ./gradlew jreleaserFullRelease


#      - name: Set up Gradle caching
#        uses: actions/cache@v3
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Grant execution permissions for gradlew
#        run: chmod +x gradlew
#
#      - name: Run Tests
#        run: ./gradlew test
